"""empty message

Revision ID: 1ef18e6158a9
Revises: a54e3d6df2ce
Create Date: 2020-09-08 08:57:45.600058

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ef18e6158a9'
down_revision = 'a54e3d6df2ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status',
               existing_type=mysql.INTEGER(),
               server_default='0',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    # ### end Alembic commands ###
