"""empty message

Revision ID: a231651503f5
Revises: df46122d963c
Create Date: 2020-09-08 09:00:44.962890

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a231651503f5'
down_revision = 'df46122d963c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    # ### end Alembic commands ###
