"""empty message

Revision ID: a54e3d6df2ce
Revises: b2f5f8784b38
Create Date: 2020-09-08 08:56:38.405371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a54e3d6df2ce'
down_revision = 'b2f5f8784b38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status',
               existing_type=mysql.INTEGER(),
               server_default='1',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###
