"""empty message

Revision ID: b2f5f8784b38
Revises: 67c05bc0da6b
Create Date: 2020-09-08 08:50:17.167594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2f5f8784b38'
down_revision = '67c05bc0da6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)
    # ### end Alembic commands ###
